DROP TABLE IF EXISTS Student;

  CREATE TABLE Student (
    EMP_ID INT AUTO_INCREMENT  PRIMARY KEY,
    FIRST_NAME VARCHAR(250) NOT NULL,
    LAST_NAME VARCHAR(250) NOT NULL,
    EMAIL_ID VARCHAR(250) DEFAULT NULL
  );